
HAL=	$(src)/../hal
ATH_HAL=$(src)/../ath_hal
NET=	net
WLAN=	${NET}/net80211
COMPAT=	${WLAN}/compat

INCS=	-include ${COMPAT}/compat.h -I${COMPAT}
EXTRA_CFLAGS+=	${INCS} -I${HAL} -I${HAL}/linux -I${ATH_HAL} -I${WLAN} -I${NET}
ifdef HAL_OBJDIR
EXTRA_CFLAGS+=	-I${HAL_OBJDIR}		# for opt_ah.h
endif

obj-$(CONFIG_ATHEROS)		+= if_ath.o if_ath_pci.o
