#
# Makefile for the IEEE 802.11 layer.
#

COMPAT=	net/net80211/compat
NET=	net

EXTRA_CFLAGS+=	-include ${COMPAT}/compat.h -I${COMPAT} -I${NET}

obj-$(CONFIG_WLAN) += wlan.o

wlan-y			:= ieee80211.o ieee80211_crypto.o \
			   ieee80211_input.o ieee80211_node.o \
			   ieee80211_output.o ieee80211_proto.o \
			   ieee80211_wireless.o ieee80211_linux.o \
			   ieee80211_dot1x.o ieee80211_radius.o \
			   if_media.o rc4.o
