#
# Makefile for the Atheros WLAN driver.
#

HAL=	$(src)/../hal
ATH_HAL=$(src)/../_ath_hal
NET=	net
WLAN=	${NET}/net80211
COMPAT=	${WLAN}/compat

INCS=	-include ${COMPAT}/compat.h -I${COMPAT}
EXTRA_CFLAGS+=	${INCS} -I${HAL} -I${HAL}/linux -I${ATH_HAL} -I${WLAN} -I${NET}

obj-$(CONFIG_ATHEROS) += ath_pci.o

ath_pci-objs	:= if_ath.o if_ath_pci.o
##2.4##export-objs	:= if_ath_pci.o
##2.4##list-multi	:= ath_pci.o

#ath_pci.o: ${ath_pci-objs}
#	$(LD) -o ath_pci.$(KMODSUF) -r $(ath_pci-objs)
