#	$P4$
#
DESTDIR=
#
# Path to the HAL source code.
#
HAL=	../hal
#
# Path to the build area for the HAL.
#
ATH_HAL=../ath_hal
#
# Path to the 802.11 include files
#
WLAN=	../wlan
#
# Path to the Linux kernel include files.
#
VERSION=	2.4.20
LINUX=	../../linux-${VERSION}/include

COPTS=	-g -O
