
# Added by Madwifi
obj-$(CONFIG_ATHEROS_HAL)		+= _ath_hal/
obj-$(CONFIG_ATHEROS)			+= ath/
obj-$(CONFIG_NET80211)			+= net80211/
obj-$(CONFIG_ATHEROS_RATE_SAMPLE)	+= _ath_rate/sample/
obj-$(CONFIG_ATHEROS_RATE_ONOE)		+= _ath_rate/onoe/
obj-$(CONFIG_ATHEROS_RATE_AMRR)		+= _ath_rate/amrr/
